using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RecrutementDomain.Entities
{
    public enum Country
    {
        Afghanistan ,
        AlandIslands,
        Albania ,
        Algeria,
        AmericanSamoa ,
        Andorra ,
        Angola ,
        Anguilla,
        Antarctica,
        AntiguaAndBarbuda,
        Argentina,
        Armenia,
        Aruba ,
        Australia,
        Austria,
        Azerbaijan,
        Bahamas,
        Bahrain,
        Bangladesh,
        Barbados,
        Belarus,
        Belgium,
        Belize ,
        Benin ,
        Bermuda ,
        Bhutan,
        Bolivia,
        BosniaAndHerzegovina ,
        Botswana,
        BouvetIsland,
        Brazil,
        BritishIndianOceanTerritory,
        BruneiDarussalam,
        Bulgaria,
        BurkinaFaso,
        Burundi,
        Cambodia,
        Cameroon,
        Canada,
        CapeVerde,
        CaymanIslands,
        CentralAfricanRepublic,
        Chad,
        Chile,
        China,
        ChristmasIsland,
        CocosKeelingIslands,
        Colombia,
        Comoros,
        Congo,
        CongoDemocraticRepublic ,
        CookIslands ,
        CostaRica,
        CoteDIvoire ,
        Croatia ,
        Cuba,
        Cyprus,
        CzechRepublic,
        Denmark,
        Djibouti,
        Dominica,
        DominicanRepublic ,
        Ecuador,
        Egypt ,
        ElSalvador,
        EquatorialGuinea,
        Eritrea ,
        Estonia,
        Ethiopia ,
        FalklandIslands ,
        FaroeIslands ,
        Fiji ,
        Finland ,
        France ,
        FrenchGuiana ,
        FrenchPolynesia ,
        FrenchSouthernTerritories,
        Gabon ,
        Gambia ,
        Georgia,
        Germany,
        Ghana ,
        Gibraltar ,
        Greece ,
        Greenland,
        Grenada ,
        Guadeloupe ,
        Guam ,
        Guatemala,
        Guernsey ,
        Guinea ,
        GuineaBissau ,
        Guyana ,
        Haiti ,
        HeardIslandMcdonaldIslands ,
        HolySeeVaticanCityState ,
        Honduras ,
        HongKong ,
        Hungary ,
        Iceland ,
        India ,
        Indonesia ,
        Iran ,
        Iraq ,
        Ireland ,
        IsleOfMan ,
        Israel ,
        Italy ,
        Jamaica ,
        Japan ,
        Jersey,
        Jordan ,
        Kazakhstan ,
        Kenya ,
        Kiribati ,
        Korea ,
        Kuwait ,
        Kyrgyzstan ,
        LaoPeoplesDemocraticRepublic ,
        Latvia ,
        Lebanon ,
        Lesotho ,
        Liberia ,
        LibyanArabJamahiriya ,
        Liechtenstein ,
        Lithuania ,
        Luxembourg ,
        Macao ,
        Macedonia,
        Madagascar,
        Malawi ,
        Malaysia,
        Maldives ,
        Mali,
        Malta,
        MarshallIslands,
        Martinique,
        Mauritania,
        Mauritius,
        Mayotte,
        Mexico,
        Micronesia,
        Moldova,
        Monaco ,
        Mongolia,
        Montenegro ,
        Montserrat,
        Morocco ,
        Mozambique ,
        Myanmar ,
        Namibia ,
        Nauru ,
        Nepal ,
        Netherlands,
        NetherlandsAntilles ,
        NewCaledonia ,
        NewZealand,
        Nicaragua,
        Niger ,
        Nigeria,
        Niue ,
        NorfolkIsland,
        NorthernMarianaIslands,
        Norway,
        Oman,
        Pakistan,
        Palau,
        PalestinianTerritory,
        Panama,
        PapuaNewGuinea,
        Paraguay,
        Peru,
        Philippines,
        Pitcairn,
        Poland ,
        Portugal ,
        PuertoRico ,
        Qatar ,
        Reunion ,
        Romania ,
        RussianFederation ,
        Rwanda ,
        SaintBarthelemy ,
        SaintHelena ,
        SaintKittsAndNevis ,
        SaintLucia ,
        SaintMartin ,
        SaintPierreAndMiquelon,
        SaintVincentAndGrenadines ,
        Samoa ,
        SanMarino ,
        SaoTomeAndPrincipe,
        SaudiArabia,
        Senegal ,
        Serbia ,
        Seychelles,
        SierraLeone,
        Singapore,
        Slovakia ,
        Slovenia ,
        SolomonIslands,
        Somalia ,
        SouthAfrica ,
        SouthGeorgiaAndSandwichIsl,
        Spain,
        SriLanka,
        Sudan,
        Suriname,
        SvalbardAndJanMayen,
        Swaziland,
        Sweden,
        Switzerland,
        SyrianArabRepublic,
        Taiwan,
        Tajikistan,
        Tanzania,
        Thailand ,
        TimorLeste ,
        Togo ,
        Tokelau ,
        Tonga ,
        TrinidadAndTobago ,
        Tunisia,
        Turkey ,
        Turkmenistan,
        TurksAndCaicosIslands,
        Tuvalu,
        Uganda,
        Ukraine,
        UnitedArabEmirates,
        UnitedKingdom,
        UnitedStates,
        UnitedStatesOutlyingIslands,
        Uruguay,
        Uzbekistan,
        Vanuatu,
        Venezuela,
        VietNam,
        VirginIslandsBritish,
        VirginIslandsUS,
        WallisAndFutuna,
        WesternSahara,
        Yemen,
        Zambia,
        Zimbabw 
    }
    public class Company
    {
        [Key]
        public int IdComapny { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public string Website { get; set; }
        public DateTime Since { get; set; }
        public int Teamsize { get; set; }
        public string City { get; set; }
        public string Address { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public Country Country { get; set; }
        public string linkedin { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Google { get; set; }
        public int Followers { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }

    }
}
